### ISSUE TITLE
Makefile has local path

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#42] opened 2020-05-19 12:46 UTC
Makefile contains: //c/Users/aaron/Documents/reproducible-research

This is contradicting our own philosophy :)

**Comment by aaronpeikert** [comment] 2020-05-19 12:47
I know, that is why I hate the "Windows" Hack, it requires to change this path.
BTW //c/Users/aaron/Documents/reproducible-research doesn't even exists on my computer.

**Comment by aaronpeikert** [comment] 2020-05-19 14:45
So I would close this issue because it is the windows workaround?

**Comment by brandmaier** [comment] 2020-05-19 19:44
On reading again, I am not sure what you meant when you wrote: "Docker on Windows requires the path to be
special; therefore, you need to hand-edit the Makefile and set current_path to the
current directory"

What is "special"? And what is the "current directory"? Do you mean the project directory?

**Closed as completed** 2020-05-20 08:29 UTC

**Comment by aaronpeikert** [comment] 2020-05-20 09:54
The core problem is to automatically get a path formatted as `C:/users/foo` within make. I just cannot figure this one out. Tried for day...
Maybe we ask around for help with that issue (in the mattermost-shell chat)?

**Comment by brandmaier** [comment] 2020-05-20 10:01
Good idea. Maybe also stack exchange or similar?
